services:
  backend:
    container_name: django
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/project
  
  frontend:
    container_name: vue
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/project/frontend
      - exclude:/project/frontend/node_modules/
    depends_on:
      - backend

volumes:
  exclude:
