# Generated by Django 5.0.1 on 2024-01-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_table_qr_code_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='token',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='TableToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_token', to='restaurant.table')),
            ],
        ),
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
