# Generated by Django 5.0.1 on 2024-01-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_table_token_tabletoken_delete_qrcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableToken',
        ),
    ]
