# Generated by Django 5.0.1 on 2024-01-17 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_orderitemvariant_order_item_tab_order_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tab',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
